# Generated by Django 3.0.8 on 2020-07-24 07:40

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', markdownx.models.MarkdownxField(help_text='Markdown形式で書いてください。', verbose_name='本文')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開可能か?')),
                ('description', models.TextField(max_length=130, verbose_name='記事の説明')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
