# Generated by Django 3.0.8 on 2020-08-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('situmon', '0005_auto_20200808_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='situmon.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='situmon.Comment'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(),
        ),
    ]
