# Generated by Django 3.0.8 on 2020-08-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situmon', '0007_auto_20200810_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_public',
        ),
    ]
